- name: Configure port on Cisco switch
  hosts: "{{ target_host }}"
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    # Turn off the interface briefly so that when it turns back on, the client
    # acquires a new DHCP lease.
    - name: Turn off interface
      ios_config:
        lines:
          - shutdown
        parents: interface {{ interface }}

    - name: Configure and turn on interface
      ios_config:
        lines:
          - description {{ port_name }}
          - switchport mode access
          - switchport access vlan {{ vlan_id }}
          - spanning-tree portfast
          - no shutdown
        parents: interface {{ interface }}

