---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Configure switch port for VLAN
      condition: true
      action:
        run_playbook:
          name: /data/configure_ports.yml
          extra_vars:
            target_host: "{{ event.payload.data.device.name }}"
            vlan_id: "{{ event.payload.data.untagged_vlan.vid }}"
            interface: "{{ event.payload.data.display }}"
            port_name: "{{ event.payload.data.link_peers[0].device.name }}"
